// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgphupylxstqifzyijzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRncGh1cHlseHN0cWlmenlpanp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDk1MDksImV4cCI6MjA2NjE4NTUwOX0.k1aOgg3Az_d9KL2k9bdi9NqAkWr6KydzxqKsiRUpfls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);